; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-LE
; RUN: llc -mtriple=aarch64_be %s -o - | FileCheck %s --check-prefixes=CHECK,CHECK-BE
; RUN: llc -mtriple=aarch64 -global-isel=1 %s -o - | FileCheck %s --check-prefixes=CHECK-GI,CHECK-LE-GI
; RUN: llc -mtriple=aarch64_be -global-isel=1 -global-isel-abort=0 %s -o - | FileCheck %s --check-prefixes=CHECK-GI,CHECK-BE-GI

@x = common dso_local global i128 0
@y = common dso_local global i128 0

define void @test1() {
; CHECK-LABEL: test1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, x
; CHECK-NEXT:    add x8, x8, :lo12:x
; CHECK-NEXT:    adrp x10, y
; CHECK-NEXT:    add x10, x10, :lo12:y
; CHECK-NEXT:    ldp x8, x9, [x8]
; CHECK-NEXT:    stp x8, x9, [x10]
; CHECK-NEXT:    ret
;
; CHECK-GI-LABEL: test1:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    adrp x8, x
; CHECK-GI-NEXT:    ldr q0, [x8, :lo12:x]
; CHECK-GI-NEXT:    adrp x8, y
; CHECK-GI-NEXT:    str q0, [x8, :lo12:y]
; CHECK-GI-NEXT:    ret
  %tmp = load volatile i128, ptr @x
  store volatile i128 %tmp, ptr @y
  ret void
}

define void @test2() {
; CHECK-LABEL: test2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, x
; CHECK-NEXT:    add x8, x8, :lo12:x
; CHECK-NEXT:    adrp x10, y
; CHECK-NEXT:    add x10, x10, :lo12:y
; CHECK-NEXT:    ldp x8, x9, [x8, #504]
; CHECK-NEXT:    stp x8, x9, [x10, #504]
; CHECK-NEXT:    ret
;
; CHECK-GI-LABEL: test2:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    adrp x8, x
; CHECK-GI-NEXT:    add x8, x8, :lo12:x
; CHECK-GI-NEXT:    add x8, x8, #504
; CHECK-GI-NEXT:    ldr q0, [x8]
; CHECK-GI-NEXT:    adrp x8, y
; CHECK-GI-NEXT:    add x8, x8, :lo12:y
; CHECK-GI-NEXT:    add x8, x8, #504
; CHECK-GI-NEXT:    str q0, [x8]
; CHECK-GI-NEXT:    ret
  %tmp = load volatile i128, ptr getelementptr (i8, ptr @x, i64 504)
  store volatile i128 %tmp, ptr getelementptr (i8, ptr @y, i64 504)
  ret void
}

define void @test3() {
; CHECK-LABEL: test3:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, x
; CHECK-NEXT:    add x8, x8, :lo12:x
; CHECK-NEXT:    adrp x10, y
; CHECK-NEXT:    add x10, x10, :lo12:y
; CHECK-NEXT:    add x8, x8, #512
; CHECK-NEXT:    ldp x8, x9, [x8]
; CHECK-NEXT:    add x10, x10, #512
; CHECK-NEXT:    stp x8, x9, [x10]
; CHECK-NEXT:    ret
;
; CHECK-GI-LABEL: test3:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    adrp x8, x
; CHECK-GI-NEXT:    add x8, x8, :lo12:x
; CHECK-GI-NEXT:    ldr q0, [x8, #512]
; CHECK-GI-NEXT:    adrp x8, y
; CHECK-GI-NEXT:    add x8, x8, :lo12:y
; CHECK-GI-NEXT:    str q0, [x8, #512]
; CHECK-GI-NEXT:    ret
  %tmp = load volatile i128, ptr getelementptr (i8, ptr @x, i64 512)
  store volatile i128 %tmp, ptr getelementptr (i8, ptr @y, i64 512)
  ret void
}

define void @test4() {
; CHECK-LABEL: test4:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, x
; CHECK-NEXT:    add x8, x8, :lo12:x
; CHECK-NEXT:    adrp x10, y
; CHECK-NEXT:    add x10, x10, :lo12:y
; CHECK-NEXT:    ldp x8, x9, [x8, #-512]
; CHECK-NEXT:    stp x8, x9, [x10, #-512]
; CHECK-NEXT:    ret
;
; CHECK-GI-LABEL: test4:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    adrp x8, x
; CHECK-GI-NEXT:    add x8, x8, :lo12:x
; CHECK-GI-NEXT:    sub x8, x8, #512
; CHECK-GI-NEXT:    ldr q0, [x8]
; CHECK-GI-NEXT:    adrp x8, y
; CHECK-GI-NEXT:    add x8, x8, :lo12:y
; CHECK-GI-NEXT:    sub x8, x8, #512
; CHECK-GI-NEXT:    str q0, [x8]
; CHECK-GI-NEXT:    ret
  %tmp = load volatile i128, ptr getelementptr (i8, ptr @x, i64 -512)
  store volatile i128 %tmp, ptr getelementptr (i8, ptr @y, i64 -512)
  ret void
}

define void @test5() {
; CHECK-LABEL: test5:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, x
; CHECK-NEXT:    add x8, x8, :lo12:x
; CHECK-NEXT:    adrp x10, y
; CHECK-NEXT:    add x10, x10, :lo12:y
; CHECK-NEXT:    sub x8, x8, #520
; CHECK-NEXT:    ldp x8, x9, [x8]
; CHECK-NEXT:    sub x10, x10, #520
; CHECK-NEXT:    stp x8, x9, [x10]
; CHECK-NEXT:    ret
;
; CHECK-GI-LABEL: test5:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    adrp x8, x
; CHECK-GI-NEXT:    add x8, x8, :lo12:x
; CHECK-GI-NEXT:    sub x8, x8, #520
; CHECK-GI-NEXT:    ldr q0, [x8]
; CHECK-GI-NEXT:    adrp x8, y
; CHECK-GI-NEXT:    add x8, x8, :lo12:y
; CHECK-GI-NEXT:    sub x8, x8, #520
; CHECK-GI-NEXT:    str q0, [x8]
; CHECK-GI-NEXT:    ret
  %tmp = load volatile i128, ptr getelementptr (i8, ptr @x, i64 -520)
  store volatile i128 %tmp, ptr getelementptr (i8, ptr @y, i64 -520)
  ret void
}

define void @test6() {
; CHECK-LABEL: test6:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, x
; CHECK-NEXT:    add x8, x8, :lo12:x
; CHECK-NEXT:    adrp x10, y
; CHECK-NEXT:    add x10, x10, :lo12:y
; CHECK-NEXT:    sub x8, x8, #520
; CHECK-NEXT:    ldp x8, x9, [x8]
; CHECK-NEXT:    sub x10, x10, #520
; CHECK-NEXT:    stp x8, x9, [x10]
; CHECK-NEXT:    ret
;
; CHECK-GI-LABEL: test6:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    adrp x8, x
; CHECK-GI-NEXT:    add x8, x8, :lo12:x
; CHECK-GI-NEXT:    sub x8, x8, #520
; CHECK-GI-NEXT:    ldr q0, [x8]
; CHECK-GI-NEXT:    adrp x8, y
; CHECK-GI-NEXT:    add x8, x8, :lo12:y
; CHECK-GI-NEXT:    sub x8, x8, #520
; CHECK-GI-NEXT:    str q0, [x8]
; CHECK-GI-NEXT:    ret
  %tmp = load volatile i128, ptr getelementptr (i8, ptr @x, i64 -520)
  store volatile i128 %tmp, ptr getelementptr (i8, ptr @y, i64 -520)
  ret void
}

define void @test7() {
; CHECK-LABEL: test7:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, x
; CHECK-NEXT:    add x8, x8, :lo12:x
; CHECK-NEXT:    adrp x10, y
; CHECK-NEXT:    add x10, x10, :lo12:y
; CHECK-NEXT:    add x8, x8, #503
; CHECK-NEXT:    ldp x8, x9, [x8]
; CHECK-NEXT:    add x10, x10, #503
; CHECK-NEXT:    stp x8, x9, [x10]
; CHECK-NEXT:    ret
;
; CHECK-GI-LABEL: test7:
; CHECK-GI:       // %bb.0:
; CHECK-GI-NEXT:    adrp x8, x
; CHECK-GI-NEXT:    add x8, x8, :lo12:x
; CHECK-GI-NEXT:    add x8, x8, #503
; CHECK-GI-NEXT:    ldr q0, [x8]
; CHECK-GI-NEXT:    adrp x8, y
; CHECK-GI-NEXT:    add x8, x8, :lo12:y
; CHECK-GI-NEXT:    add x8, x8, #503
; CHECK-GI-NEXT:    str q0, [x8]
; CHECK-GI-NEXT:    ret
  %tmp = load volatile i128, ptr getelementptr (i8, ptr @x, i64 503)
  store volatile i128 %tmp, ptr getelementptr (i8, ptr @y, i64 503)
  ret void
}

define i128 @load_nonvol(i32, i32, ptr %p) {
; CHECK-LABEL: load_nonvol:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ldp x0, x1, [x2]
; CHECK-NEXT:    ret
;
; CHECK-LE-GI-LABEL: load_nonvol:
; CHECK-LE-GI:       // %bb.0: // %entry
; CHECK-LE-GI-NEXT:    ldr q0, [x2]
; CHECK-LE-GI-NEXT:    mov d1, v0.d[1]
; CHECK-LE-GI-NEXT:    fmov x0, d0
; CHECK-LE-GI-NEXT:    fmov x1, d1
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: load_nonvol:
; CHECK-BE-GI:       // %bb.0: // %entry
; CHECK-BE-GI-NEXT:    ldr q0, [x2]
; CHECK-BE-GI-NEXT:    mov d1, v0.d[1]
; CHECK-BE-GI-NEXT:    fmov x1, d0
; CHECK-BE-GI-NEXT:    fmov x0, d1
; CHECK-BE-GI-NEXT:    ret
entry:
  %l = load i128, ptr %p, align 16
  ret i128 %l
}

define i128 @load_vol(i32, i32, ptr %p) {
; CHECK-LABEL: load_vol:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ldp x0, x1, [x2]
; CHECK-NEXT:    ret
;
; CHECK-LE-GI-LABEL: load_vol:
; CHECK-LE-GI:       // %bb.0: // %entry
; CHECK-LE-GI-NEXT:    ldr q0, [x2]
; CHECK-LE-GI-NEXT:    mov d1, v0.d[1]
; CHECK-LE-GI-NEXT:    fmov x0, d0
; CHECK-LE-GI-NEXT:    fmov x1, d1
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: load_vol:
; CHECK-BE-GI:       // %bb.0: // %entry
; CHECK-BE-GI-NEXT:    ldr q0, [x2]
; CHECK-BE-GI-NEXT:    mov d1, v0.d[1]
; CHECK-BE-GI-NEXT:    fmov x1, d0
; CHECK-BE-GI-NEXT:    fmov x0, d1
; CHECK-BE-GI-NEXT:    ret
entry:
  %l = load volatile i128, ptr %p, align 16
  ret i128 %l
}

define void @store_nonvol(i128 %a, ptr %p) {
; CHECK-LABEL: store_nonvol:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp x0, x1, [x2]
; CHECK-NEXT:    ret
;
; CHECK-LE-GI-LABEL: store_nonvol:
; CHECK-LE-GI:       // %bb.0: // %entry
; CHECK-LE-GI-NEXT:    mov v0.d[0], x0
; CHECK-LE-GI-NEXT:    mov v0.d[1], x1
; CHECK-LE-GI-NEXT:    str q0, [x2]
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: store_nonvol:
; CHECK-BE-GI:       // %bb.0: // %entry
; CHECK-BE-GI-NEXT:    mov v0.d[0], x1
; CHECK-BE-GI-NEXT:    mov v0.d[1], x0
; CHECK-BE-GI-NEXT:    str q0, [x2]
; CHECK-BE-GI-NEXT:    ret
entry:
  store i128 %a, ptr %p, align 16
  ret void
}

define void @loadstore_vol(i128 %a, ptr %p) {
; CHECK-LABEL: loadstore_vol:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp x0, x1, [x2]
; CHECK-NEXT:    ret
;
; CHECK-LE-GI-LABEL: loadstore_vol:
; CHECK-LE-GI:       // %bb.0: // %entry
; CHECK-LE-GI-NEXT:    mov v0.d[0], x0
; CHECK-LE-GI-NEXT:    mov v0.d[1], x1
; CHECK-LE-GI-NEXT:    str q0, [x2]
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: loadstore_vol:
; CHECK-BE-GI:       // %bb.0: // %entry
; CHECK-BE-GI-NEXT:    mov v0.d[0], x1
; CHECK-BE-GI-NEXT:    mov v0.d[1], x0
; CHECK-BE-GI-NEXT:    str q0, [x2]
; CHECK-BE-GI-NEXT:    ret
entry:
  store volatile i128 %a, ptr %p, align 16
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-BE: {{.*}}
; CHECK-LE: {{.*}}
