; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-linux-gnu    | FileCheck %s --check-prefixes=CHECK
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64_be-linux-gnu | FileCheck %s  --check-prefixes=CHECK
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-linux-gnu    -mcpu=exynos-m3 | FileCheck %s --check-prefixes=CHECK
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64_be-linux-gnu -mcpu=exynos-m3 | FileCheck %s --check-prefixes=CHECK
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-linux-gnu -global-isel=1 | FileCheck %s --check-prefixes=CHECK
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64_be-linux-gnu -global-isel=1 -global-isel-abort=0 | FileCheck %s  --check-prefixes=CHECK-BE

define void @test_split_f(<4 x float> %val, ptr %addr) {
; CHECK-LABEL: test_split_f:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
;
; CHECK-BE-LABEL: test_split_f:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    st1 { v0.4s }, [x0]
; CHECK-BE-NEXT:    ret
  store <4 x float> %val, ptr %addr, align 8
  ret void
}

define void @test_split_d(<2 x double> %val, ptr %addr) {
; CHECK-LABEL: test_split_d:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
;
; CHECK-BE-LABEL: test_split_d:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    st1 { v0.2d }, [x0]
; CHECK-BE-NEXT:    ret
  store <2 x double> %val, ptr %addr, align 8
  ret void
}

define void @test_split_128(fp128 %val, ptr %addr) {
; CHECK-LABEL: test_split_128:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str q0, [x0]
; CHECK-NEXT:    ret
;
; CHECK-BE-LABEL: test_split_128:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str q0, [x0]
; CHECK-BE-NEXT:    ret
  store fp128 %val, ptr %addr, align 8
  ret void
}
